# Generated by Django 5.0.6 on 2024-06-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
    ]
