# Generated by Django 5.0.6 on 2024-06-25 09:57

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_postmodel_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('post_image', models.ImageField(upload_to='blogs')),
                ('like_number', models.IntegerField(default=0)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('categories', models.ManyToManyField(to='blogapp.categorymodel')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blogmodel'),
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
