# Generated by Django 5.0.6 on 2024-06-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_blogmodel_alter_commentmodel_post_delete_postmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
