# Generated by Django 5.0.6 on 2024-06-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_alter_blogmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='post_image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blogmodel',
            old_name='post_name',
            new_name='blog_name',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='post',
            new_name='blog',
        ),
    ]
