# Generated by Django 5.0.6 on 2024-06-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_rename_post_image_blogmodel_blog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_image',
        ),
    ]
