# Generated by Django 5.0.6 on 2024-06-24 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About Us Page'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact Us Page'},
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
