# Generated by Django 5.0.6 on 2024-06-25 09:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_aboutmodel_options_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
